export const networkFixture = {
  city: "Metrovale",
  fictional: true,
  notice: "Metrovale is a fictional demonstration network.",
  network_version: "metrovale-2026.08.1",
  disruption_version: "none",
  stations: [
    { id: "northgate", name: "Northgate", accessible: true, lines: ["red"], x: 12, y: 8 },
    { id: "museum", name: "Museum Quarter", accessible: true, lines: ["orange", "red", "violet"], x: 28, y: 22 },
    { id: "central", name: "Central Station", accessible: true, lines: ["blue", "red"], x: 45, y: 36 },
    { id: "old-town", name: "Old Town", accessible: false, lines: ["blue", "green"], x: 31, y: 43 },
    { id: "riverfront", name: "Riverfront", accessible: true, lines: ["red", "green"], x: 58, y: 48 },
    { id: "east-market", name: "East Market", accessible: true, lines: ["blue"], x: 61, y: 31 },
    { id: "university", name: "Metrovale University", accessible: true, lines: ["blue", "orange", "violet"], x: 74, y: 27 },
    { id: "tech-park", name: "Tech Park", accessible: true, lines: ["blue", "orange"], x: 88, y: 24 },
    { id: "gardens", name: "Civic Gardens", accessible: false, lines: ["green", "violet"], x: 42, y: 59 },
    { id: "harbor", name: "Harbor Point", accessible: true, lines: ["green", "orange"], x: 79, y: 63 },
    { id: "stadium", name: "Stadium", accessible: true, lines: ["orange", "red", "violet"], x: 76, y: 47 },
    { id: "airport", name: "Metrovale Airport", accessible: true, lines: ["green", "red"], x: 94, y: 51 },
    { id: "west-end", name: "West End", accessible: true, lines: ["blue"], x: 12, y: 44 },
    { id: "hillcrest", name: "Hillcrest", accessible: true, lines: ["green"], x: 24, y: 67 },
  ],
  lines: [
    { id: "red", name: "Red Line", color: "#ef4444" },
    { id: "blue", name: "Blue Line", color: "#3b82f6" },
    { id: "green", name: "Green Line", color: "#22c55e" },
    { id: "orange", name: "Orange Connector", color: "#f97316" },
    { id: "violet", name: "Violet Line", color: "#8b5cf6" },
  ],
  connections: [
    { from_station_id: "northgate", to_station_id: "museum", line_id: "red", travel_minutes: 4, accessible: true },
    { from_station_id: "museum", to_station_id: "central", line_id: "red", travel_minutes: 4, accessible: true },
    { from_station_id: "central", to_station_id: "riverfront", line_id: "red", travel_minutes: 4, accessible: true },
    { from_station_id: "riverfront", to_station_id: "stadium", line_id: "red", travel_minutes: 4, accessible: true },
    { from_station_id: "stadium", to_station_id: "airport", line_id: "red", travel_minutes: 6, accessible: true },
    { from_station_id: "west-end", to_station_id: "old-town", line_id: "blue", travel_minutes: 5, accessible: true },
    { from_station_id: "old-town", to_station_id: "central", line_id: "blue", travel_minutes: 4, accessible: false },
    { from_station_id: "central", to_station_id: "east-market", line_id: "blue", travel_minutes: 4, accessible: true },
    { from_station_id: "east-market", to_station_id: "university", line_id: "blue", travel_minutes: 4, accessible: true },
    { from_station_id: "university", to_station_id: "tech-park", line_id: "blue", travel_minutes: 5, accessible: true },
    { from_station_id: "hillcrest", to_station_id: "gardens", line_id: "green", travel_minutes: 5, accessible: false },
    { from_station_id: "gardens", to_station_id: "old-town", line_id: "green", travel_minutes: 4, accessible: false },
    { from_station_id: "old-town", to_station_id: "riverfront", line_id: "green", travel_minutes: 5, accessible: false },
    { from_station_id: "riverfront", to_station_id: "harbor", line_id: "green", travel_minutes: 6, accessible: true },
    { from_station_id: "harbor", to_station_id: "airport", line_id: "green", travel_minutes: 7, accessible: true },
    { from_station_id: "museum", to_station_id: "gardens", line_id: "violet", travel_minutes: 6, accessible: false },
    { from_station_id: "gardens", to_station_id: "university", line_id: "violet", travel_minutes: 6, accessible: false },
    { from_station_id: "university", to_station_id: "stadium", line_id: "violet", travel_minutes: 5, accessible: true },
    { from_station_id: "museum", to_station_id: "university", line_id: "orange", travel_minutes: 10, accessible: true },
    { from_station_id: "tech-park", to_station_id: "harbor", line_id: "orange", travel_minutes: 6, accessible: true },
    { from_station_id: "harbor", to_station_id: "stadium", line_id: "orange", travel_minutes: 5, accessible: true },
  ],
};

export const scenariosFixture = {
  scenarios: [
    {
      id: "central-closure",
      name: "Central Station closes",
      summary: "An emergency inspection closes Central Station. Trains cannot stop there.",
      kind: "station_closure",
      rider_impact: "Northgate to Airport must avoid Central and use another set of lines.",
      suggested_trip: { origin_id: "northgate", destination_id: "airport", objective: "fastest" },
      closed_station_ids: ["central"],
      inaccessible_station_ids: [],
      line_delays: [],
      disruption_version: "disruption-central-closure-v1",
    },
    {
      id: "red-line-delay",
      name: "Red Line slows down",
      summary: "A signal problem adds four minutes to every Red Line segment.",
      kind: "line_delay",
      rider_impact: "The usual Red Line trip becomes slower, so another line may be faster.",
      suggested_trip: { origin_id: "northgate", destination_id: "airport", objective: "fastest" },
      closed_station_ids: [],
      inaccessible_station_ids: [],
      line_delays: [{ line_id: "red", delay_minutes: 4 }],
      disruption_version: "disruption-red-delay-v1",
    },
    {
      id: "accessibility-outage",
      name: "Central elevators stop working",
      summary: "Trains still stop at Central, but its elevators are unavailable.",
      kind: "accessibility_outage",
      rider_impact: "A no-stairs trip cannot use Central until its elevators are working.",
      suggested_trip: { origin_id: "northgate", destination_id: "airport", objective: "accessible" },
      closed_station_ids: [],
      inaccessible_station_ids: ["central"],
      line_delays: [],
      disruption_version: "disruption-accessibility-v1",
    },
    {
      id: "riverfront-closure",
      name: "Riverfront closes",
      summary: "A safety check closes Riverfront. Trains cannot stop or pass through it.",
      kind: "station_closure",
      rider_impact: "Central Station to Harbor Point must go around Riverfront.",
      suggested_trip: { origin_id: "central", destination_id: "harbor", objective: "fastest" },
      closed_station_ids: ["riverfront"],
      inaccessible_station_ids: [],
      line_delays: [],
      disruption_version: "disruption-riverfront-closure-v1",
    },
    {
      id: "harbor-flooding",
      name: "Harbor Point closes after flooding",
      summary: "Flooding closes Harbor Point. Trains cannot stop or pass through it.",
      kind: "station_closure",
      rider_impact: "Tech Park to the airport must avoid the connection through Harbor Point.",
      suggested_trip: { origin_id: "tech-park", destination_id: "airport", objective: "fastest" },
      closed_station_ids: ["harbor"],
      inaccessible_station_ids: [],
      line_delays: [],
      disruption_version: "disruption-harbor-flooding-v1",
    },
    {
      id: "blue-line-track-work",
      name: "Blue Line slows during track work",
      summary: "Track work adds three minutes to every Blue Line segment.",
      kind: "line_delay",
      rider_impact: "West End to Tech Park may be faster on other lines while work continues.",
      suggested_trip: { origin_id: "west-end", destination_id: "tech-park", objective: "fastest" },
      closed_station_ids: [],
      inaccessible_station_ids: [],
      line_delays: [{ line_id: "blue", delay_minutes: 3 }],
      disruption_version: "disruption-blue-track-work-v1",
    },
    {
      id: "green-line-bridge-check",
      name: "Green Line slows for a bridge check",
      summary: "A bridge inspection adds three minutes to every Green Line segment.",
      kind: "line_delay",
      rider_impact: "Hillcrest to the airport may switch away from the Green Line.",
      suggested_trip: { origin_id: "hillcrest", destination_id: "airport", objective: "fastest" },
      closed_station_ids: [],
      inaccessible_station_ids: [],
      line_delays: [{ line_id: "green", delay_minutes: 3 }],
      disruption_version: "disruption-green-bridge-v1",
    },
    {
      id: "university-elevator-outage",
      name: "University elevators stop working",
      summary: "Trains still stop at Metrovale University, but its elevators are unavailable.",
      kind: "accessibility_outage",
      rider_impact: "A no-stairs trip from Museum Quarter to Tech Park must avoid the university.",
      suggested_trip: { origin_id: "museum", destination_id: "tech-park", objective: "accessible" },
      closed_station_ids: [],
      inaccessible_station_ids: ["university"],
      line_delays: [],
      disruption_version: "disruption-university-accessibility-v1",
    },
  ],
};

const station = (id: string, name: string) => ({ id, name });

export const comparisonFixture = {
  run_id: "01J6N7R8TESTROUTEWISE",
  baseline: {
    station_ids: ["northgate", "museum", "central", "riverfront", "stadium", "airport"],
    stations: [
      station("northgate", "Northgate"),
      station("museum", "Museum Quarter"),
      station("central", "Central Station"),
      station("riverfront", "Riverfront"),
      station("stadium", "Stadium"),
      station("airport", "Metrovale Airport"),
    ],
    legs: [
      { from_station_id: "northgate", from_station_name: "Northgate", to_station_id: "museum", to_station_name: "Museum Quarter", line_id: "red", line_name: "Red Line", base_minutes: 4, delay_minutes: 0, transfer_wait_minutes: 0, minutes: 4, accessible: true },
      { from_station_id: "museum", from_station_name: "Museum Quarter", to_station_id: "central", to_station_name: "Central Station", line_id: "red", line_name: "Red Line", base_minutes: 4, delay_minutes: 0, transfer_wait_minutes: 0, minutes: 4, accessible: true },
      { from_station_id: "central", from_station_name: "Central Station", to_station_id: "riverfront", to_station_name: "Riverfront", line_id: "red", line_name: "Red Line", base_minutes: 4, delay_minutes: 0, transfer_wait_minutes: 0, minutes: 4, accessible: true },
      { from_station_id: "riverfront", from_station_name: "Riverfront", to_station_id: "stadium", to_station_name: "Stadium", line_id: "red", line_name: "Red Line", base_minutes: 4, delay_minutes: 0, transfer_wait_minutes: 0, minutes: 4, accessible: true },
      { from_station_id: "stadium", from_station_name: "Stadium", to_station_id: "airport", to_station_name: "Metrovale Airport", line_id: "red", line_name: "Red Line", base_minutes: 6, delay_minutes: 0, transfer_wait_minutes: 0, minutes: 6, accessible: true },
    ],
    total_minutes: 22,
    transfers: 0,
    accessible: true,
  },
  disrupted: {
    station_ids: ["northgate", "museum", "gardens", "university", "stadium", "airport"],
    stations: [
      station("northgate", "Northgate"),
      station("museum", "Museum Quarter"),
      station("gardens", "Civic Gardens"),
      station("university", "Metrovale University"),
      station("stadium", "Stadium"),
      station("airport", "Metrovale Airport"),
    ],
    legs: [
      { from_station_id: "northgate", from_station_name: "Northgate", to_station_id: "museum", to_station_name: "Museum Quarter", line_id: "red", line_name: "Red Line", base_minutes: 4, delay_minutes: 0, transfer_wait_minutes: 0, minutes: 4, accessible: true },
      { from_station_id: "museum", from_station_name: "Museum Quarter", to_station_id: "gardens", to_station_name: "Civic Gardens", line_id: "violet", line_name: "Violet Line", base_minutes: 6, delay_minutes: 0, transfer_wait_minutes: 4, minutes: 10, accessible: false },
      { from_station_id: "gardens", from_station_name: "Civic Gardens", to_station_id: "university", to_station_name: "Metrovale University", line_id: "violet", line_name: "Violet Line", base_minutes: 6, delay_minutes: 0, transfer_wait_minutes: 0, minutes: 6, accessible: false },
      { from_station_id: "university", from_station_name: "Metrovale University", to_station_id: "stadium", to_station_name: "Stadium", line_id: "violet", line_name: "Violet Line", base_minutes: 5, delay_minutes: 0, transfer_wait_minutes: 0, minutes: 5, accessible: true },
      { from_station_id: "stadium", from_station_name: "Stadium", to_station_id: "airport", to_station_name: "Metrovale Airport", line_id: "red", line_name: "Red Line", base_minutes: 6, delay_minutes: 0, transfer_wait_minutes: 4, minutes: 10, accessible: true },
    ],
    total_minutes: 35,
    transfers: 2,
    accessible: false,
  },
  impact: { status: "rerouted", additional_minutes: 13, transfer_change: 2 },
  explanation: "Central Station is closed, so RouteWise diverts at Museum Quarter because its adjusted travel time is lowest.",
  evidence: {
    algorithm: "dijkstra",
    timing_ms: 4.321,
    objective: "fastest",
    scenario_id: "central-closure",
    network_version: "metrovale-2026.08.1",
    disruption_version: "disruption-central-closure-v1",
    constraints: { wheelchair_required: false, max_transfers: null },
    cache: { baseline_hit: false, disrupted_hit: false, invalidated_entries: 0 },
    decision_factors: [
      "Central Station was removed from the disrupted graph.",
      "The replacement has the lowest adjusted travel time.",
    ],
    replayed_from_run_id: null,
  },
};
